# Generated by Django 4.0.6 on 2022-08-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
